"""
@file settings.py
@brief Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see:
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-to*p4&j0zpmrjqdrmjg)*ci@24c@_nyz-5ook26sbry5eknflg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  /**< Django admin app */
    'django.contrib.auth',  /**< Django auth app */
    'django.contrib.contenttypes',  /**< Django content types app */
    'django.contrib.sessions',  /**< Django sessions app */
    'django.contrib.messages',  /**< Django messages app */
    'django.contrib.staticfiles',  /**< Django static files app */
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  /**< Security middleware */
    'django.contrib.sessions.middleware.SessionMiddleware',  /**< Sessions middleware */
    'django.middleware.common.CommonMiddleware',  /**< Common middleware */
    'django.middleware.csrf.CsrfViewMiddleware',  /**< CSRF view middleware */
    'django.contrib.auth.middleware.AuthenticationMiddleware',  /**< Authentication middleware */
    'django.contrib.messages.middleware.MessageMiddleware',  /**< Messages middleware */
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  /**< Clickjacking middleware */
]

ROOT_URLCONF = 'djangoProject.urls'  /**< Root URL configuration */

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  /**< Template backend */
        'DIRS': [BASE_DIR / 'templates'],  /**< Directories to search for templates */
        'APP_DIRS': True,  /**< Enable app directories */
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  /**< Debug context processor */
                'django.template.context_processors.request',  /**< Request context processor */
                'django.contrib.auth.context_processors.auth',  /**< Auth context processor */
                'django.contrib.messages.context_processors.messages',  /**< Messages context processor */
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject.wsgi.application'  /**< WSGI application configuration */


# Database configuration
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  /**< Database engine */
        'NAME': BASE_DIR / 'db.sqlite3',  /**< Database name */
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  /**< User attribute similarity validator */
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  /**< Minimum length validator */
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  /**< Common password validator */
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  /**< Numeric password validator */
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'  /**< Default language code */

TIME_ZONE = 'UTC'  /**< Default time zone */

USE_I18N = True  /**< Enable internationalization */

USE_TZ = True  /**< Enable timezone support */


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'  /**< URL to use when referring to static files */
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'djangoProject/static')  /**< Directories for static files */
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  /**< Default auto field */
